#! /bin/bash
sudo swapoff -a
sudo apt-get update
sudo apt install -y docker.io
sudo apt-get install -y apt-transport-https ca-certificates curl
#Install the Google cloud package
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
# Add repository to the /etc/apt/source.list.d
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list
sudo apt update 
sudo apt install -y kubeadm kubectl kubelet
sudo apt-mark hold kubectl kubeadm kubelet
sudo iptables -F && sudo iptables -t nat -F && sudo iptables -t mangle -F && sudo iptables -X
sudo apt daemon-reload
systemctl enable kubelet
# kubeadm join 191.168.0.4:6443 --token o3umxj.0bc2797jh2j3fp8o --discovery-token-ca-cert-hash sha256:d6b1624be2716776c77503603ed5809a96c9b211dfcf519df2db57056c56fd4a
